spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoplaptop
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: phamquocbao
      password: 123456
      
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  #default = 1MB
  servlet:
    multipart:
      max-file-size: 50MB
#default = 10 MB (form data)
      max-request-size: 50MB