spring:
  port: 8080

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoplaptop
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  #default = 1MB
  servlet:
    multipart:
      max-file-size: 50MB
      #default = 10 MB (form data)
      max-request-size: 50MB

  #config session
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
